# Generated by Django 4.1.7 on 2023-03-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rating',
            new_name='ratingAuthor',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentRating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='postRating',
            new_name='rating',
        ),
    ]
