# Generated by Django 4.1.7 on 2023-04-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_rating_author_ratingauthor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='ratComment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='ratPost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='ratPostComment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='ratingAuthorN',
            field=models.IntegerField(default=0),
        ),
    ]
