# Generated by Django 4.1.7 on 2023-04-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_author_ratcomment_author_ratpost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='ratComment',
        ),
        migrations.RemoveField(
            model_name='author',
            name='ratPost',
        ),
        migrations.RemoveField(
            model_name='author',
            name='ratPostComment',
        ),
        migrations.RemoveField(
            model_name='author',
            name='ratingAuthorN',
        ),
    ]
